const Action = {
  HELLO: 'HELLO',
  PREMASTER_SECRET_EXCHANGE: 'PREMASTER_SECRET_EXCHANGE',
  READY: 'READY',
  HANDSHAKE_END: 'HANDSHAKE_END',
  DATA_TRANSFER: 'DATA_TRANSFER',
};

export { Action };
